config/routes.rb
Rails.application.routes.draw do
  resources :climates

  resources :cities

  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :climates
  validates_presence_of :name
end

app/models/climate.rb
class Climate < ActiveRecord::Base
  belongs_to :city
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:latitude, :longitude, :country)
    end
end

app/controllers/climates_controller.rb
class ClimatesController < ApplicationController
  before_action :set_climate, only: [:show, :edit, :update, :destroy]

  # GET /climates
  # GET /climates.json
  def index
    @climates = Climate.all
  end

  # GET /climates/1
  # GET /climates/1.json
  def show
  end

  # GET /climates/new
  def new
    @climate = Climate.new
  end

  # GET /climates/1/edit
  def edit
  end

  # POST /climates
  # POST /climates.json
  def create
    @climate = Climate.new(climate_params)

    respond_to do |format|
      if @climate.save
        format.html { redirect_to @climate, notice: 'Climate was successfully created.' }
        format.json { render :show, status: :created, location: @climate }
      else
        format.html { render :new }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climates/1
  # PATCH/PUT /climates/1.json
  def update
    respond_to do |format|
      if @climate.update(climate_params)
        format.html { redirect_to @climate, notice: 'Climate was successfully updated.' }
        format.json { render :show, status: :ok, location: @climate }
      else
        format.html { render :edit }
        format.json { render json: @climate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climates/1
  # DELETE /climates/1.json
  def destroy
    @climate.destroy
    respond_to do |format|
      format.html { redirect_to climates_url, notice: 'Climate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climate
      @climate = Climate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climate_params
      params.require(:climate).permit(:temperature, :pressure, :humidity, :temperature_min, :temperature_max, :wind_speed, :wind_degrees, :clouds)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cities = City.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/climates_helper.rb
module ClimatesHelper
end

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table>
  <thead>
    <tr>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Country</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cities.each do |city| %>
      <tr>
        <td><%= city.latitude %></td>
        <td><%= city.longitude %></td>
        <td><%= city.country %></td>
        <td><%= link_to 'Show', city %></td>
        <td><%= link_to 'Edit', edit_city_path(city) %></td>
        <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New City', new_city_path %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Latitude:</strong>
  <%= @city.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @city.longitude %>
</p>

<p>
  <strong>Country:</strong>
  <%= @city.country %>
</p>

<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/climates/_form.html.erb
<%= form_for(@climate) do |f| %>
  <% if @climate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climate.errors.count, "error") %> prohibited this climate from being saved:</h2>

      <ul>
      <% @climate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :temperature %><br>
    <%= f.text_field :temperature %>
  </div>
  <div class="field">
    <%= f.label :pressure %><br>
    <%= f.text_field :pressure %>
  </div>
  <div class="field">
    <%= f.label :humidity %><br>
    <%= f.text_field :humidity %>
  </div>
  <div class="field">
    <%= f.label :temperature_min %><br>
    <%= f.text_field :temperature_min %>
  </div>
  <div class="field">
    <%= f.label :temperature_max %><br>
    <%= f.text_field :temperature_max %>
  </div>
  <div class="field">
    <%= f.label :wind_speed %><br>
    <%= f.text_field :wind_speed %>
  </div>
  <div class="field">
    <%= f.label :wind_degrees %><br>
    <%= f.text_field :wind_degrees %>
  </div>
  <div class="field">
    <%= f.label :clouds %><br>
    <%= f.text_field :clouds %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climates/edit.html.erb
<h1>Editing climate</h1>

<%= render 'form' %>

<%= link_to 'Show', @climate %> |
<%= link_to 'Back', climates_path %>

app/views/climates/index.html.erb
<h1>Listing climates</h1>

<table>
  <thead>
    <tr>
      <th>Temperature</th>
      <th>Pressure</th>
      <th>Humidity</th>
      <th>Temperature min</th>
      <th>Temperature max</th>
      <th>Wind speed</th>
      <th>Wind degrees</th>
      <th>Clouds</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climates.each do |climate| %>
      <tr>
        <td><%= climate.temperature %></td>
        <td><%= climate.pressure %></td>
        <td><%= climate.humidity %></td>
        <td><%= climate.temperature_min %></td>
        <td><%= climate.temperature_max %></td>
        <td><%= climate.wind_speed %></td>
        <td><%= climate.wind_degrees %></td>
        <td><%= climate.clouds %></td>
        <td><%= link_to 'Show', climate %></td>
        <td><%= link_to 'Edit', edit_climate_path(climate) %></td>
        <td><%= link_to 'Destroy', climate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climate', new_climate_path %>

app/views/climates/new.html.erb
<h1>New climate</h1>

<%= render 'form' %>

<%= link_to 'Back', climates_path %>

app/views/climates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Temperature:</strong>
  <%= @climate.temperature %>
</p>

<p>
  <strong>Pressure:</strong>
  <%= @climate.pressure %>
</p>

<p>
  <strong>Humidity:</strong>
  <%= @climate.humidity %>
</p>

<p>
  <strong>Temperature min:</strong>
  <%= @climate.temperature_min %>
</p>

<p>
  <strong>Temperature max:</strong>
  <%= @climate.temperature_max %>
</p>

<p>
  <strong>Wind speed:</strong>
  <%= @climate.wind_speed %>
</p>

<p>
  <strong>Wind degrees:</strong>
  <%= @climate.wind_degrees %>
</p>

<p>
  <strong>Clouds:</strong>
  <%= @climate.clouds %>
</p>

<%= link_to 'Edit', edit_climate_path(@climate) %> |
<%= link_to 'Back', climates_path %>

app/views/home/index.html.erb
<table>
  <thead>
    <th>Name</th>
    <th>Temperatue</th>
  </thead>
  <tbody>
    <% @cities.each do |city| %>
    <tr>
      <td><%= city.name -%></td>
      <td><%= city.climates.last.temperature -%></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>